name: Test Build
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_SDK_VERSION: 5.0.x

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet_version: [ '5.0.x' ]
        os: [ windows-latest ]

    name: Build on ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Setup .NET SDK (${{ matrix.dotnet_version }})
        if: success()
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: ${{ matrix.dotnet_version }}

      - name: Restore dependencies
        if: success()
        run: dotnet restore

      - name: Build solution
        if: success()
        run: dotnet build --configuration Debug --no-restore
