name: Build
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_SDK_VERSION: 5.0.x

on:
  push:
    branches: [ main ]

jobs:
  Build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GPR_TOKEN_READ_PACKAGES }}

    - name: Restore dependencies
      run: dotnet restore
      env:
        DNGLUA_GPR_AUTH_TOKEN: ${{ secrets.GPR_TOKEN_READ_PACKAGES }}

    - name: Build solution
      run: dotnet build --configuration Debug --no-restore

    #- name: Run tests
    #  run: dotnet test --configuration Debug --no-build --no-restore
